apiVersion: apps/v1
kind: Deployment
metadata:
  name:  auth
  namespace: default
  labels:
    app:  auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app:  auth
    spec:
      containers:
      - name:  auth
        image:  rajesh2001/auth:0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: auth-configmap
        - secretRef:
            name: auth-secret
        ports:
        - containerPort:  5000
      restartPolicy: Always