apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: auth
    protocol: TCP
    port: 5000
    targetPort: 5000 