"""This file contains the definition of the Model(Tables of Database)"""

from sqlalchemy import Column, Integer, String, Sequence
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

class UserModel(Base):
    __tablename__ = "users"
    """
    Configuration Model for User

    Fields:
        id (int): Unique key generated by sequence generator.
        name (str): The user's name.
        email (str): The user's email address.
        number (int): The user's phone number.
        password (str): The user's password (plain text).
        address (str): The user's address.
        salt(str): A salt for password hashing and validation.

    """
    id = Column(Integer, Sequence('user_id_seq'), primary_key=True)
    name = Column(String)
    address = Column(String)
    email = Column(String, unique=True)
    number = Column(Integer, unique=True)
    password = Column(String)
    salt = Column(String)
